### PR TITLE
adding ft1 segment and rspec  test

### PR DESCRIPTION
**Pull request by raulperezalejo**
Hello guys i am currently working  on implementing some HL7 messages and this gem  has been very useful. I have to send this segment and realize that is not in the gem, so here is to your consideration.

### CODE REVIEW

**Comment by mogox** [comment]
Looks good but I'm not familiar with the FT1 segment.  @raulperezalejo do you have a source that validates that this is segment is in the standard?
The best I found was this: http://www.hl7.eu/refactored/segFT1.html  

@mitch-lindsay Are you familiar with the FT1 Segment?

**Comment by raulperezalejo** [comment]
The example i used to make the unit test was provided by an HL7 provider to develop the segment. Would be great if someone else validate it.

**Comment by mitch-lindsay** [comment]
This looks good.  @raulperezalejo  The only ask I have is if you could add field entries for the missing fields.  We will be using the FT1 segment for a future project and I know we will need FT1:16 at least.

**Comment by raulperezalejo** [comment]
Hello @mitch-lindsay, i have added all fields from http://www.hl7.eu/refactored/segFT1.html into the ft1 segment file. I don´t have such a big segment to test, added by hand the FT1:16, let me know if more fields test are needed.

**Pull request merged**
