### PR TITLE
Add TXA segment

### PR DESCRIPTION
**Pull request by rodrigofhm**
Used as reference:

https://hl7-definition.caristix.com/v2/HL7v2.8/Segments/TXA

### CODE REVIEW

**Review by Stratus3D — APPROVED** [review]

**Comment by Stratus3D** [comment]
Thanks for the PR @rodrigofhm ! Unfortunately it doesn't look like any of the other maintainers have been active in about a year, so I'm not certain what the status of this repo is. I don't see any harm in your changes though, so unless someone objects I'll merge it tomorrow.

**Comment by mitch-lindsay** [comment]
@rodrigofhm It would be great to see a spec for the new segment but otherwise this looks good to me.

**Comment by rodrigofhm** [comment]
Thanks for reviewing @Stratus3D! 

@mitch-lindsay Yes agree, I'll add a spec for it.

**Review by Stratus3D — APPROVED** [review]
Tests look good to me.

**Review by mitch-lindsay — APPROVED** [review]

**Comment by rodrigofhm** [comment]
Hi @Stratus3D, thanks for reviewing and merging this one.

We use this gem on our project and wanted to know if you plan to publish another version of this gem soon?

**Comment by mitch-lindsay** [comment]
@rodrigofhm I'll work on releasing a new minor version update of this gem.

**Pull request merged**
