### PR TITLE
Remove non-standard ZCF segment

### PR DESCRIPTION
**Pull request by rclavel**
Hi,

The ZCF segment present in this gem conflicts with a custom segment I have implemented.
This segment is not in the standard ([reference](https://corepointhealth.com/resource-center/hl7-resources/hl7-z-segments)) and should be removed.

If someone want to define its own ZXX segment, it is possible to add his specific class in his project.

### CODE REVIEW

**Comment by mogox** [comment]
Ahhh good catch! that ZCF segment has been there for a while.  @mitch-lindsay I think we need to extract this into a different gem like we did with ZPS.  Before merging and releasing this, it'd be great to have another option for users who are using this segment.

**Comment by rclavel** [comment]
Maybe a different gem is not necessary, you can still extend the gem classes. For example I use an initializer in my Rails app to load the gem and define my custom segments:
```ruby
# config/initializers/extensions/ruby_hl7_ext.rb
require 'ruby-hl7'

class HL7::Message::Segment::ZCF < HL7::Message::Segment
  weight 1000
  add_field :id
  add_field :ownership
  add_field :value
end
```
I would like to add a proper initializer to this gem to define custom segments instead of doing this monkey-patching, I'll try if I find the time to do it 🙂

**Comment by mogox** [comment]
Yeah, I agree with having a proper initializer.
The issue that I see is that users who had installed the gem and depend on the `ZCF` segment will have to add this class manually if they want to update to the next version of the gem.  I feel that something more friendly would be to add the custom segment to their Gemfile as we do it with other customs segments we have available.  

I'd like to hear from someone else on the @ruby-hl7/contributors  team 😄

**Comment by rclavel** [comment]
I understand your issue. What did you do for the `ZPF` segment? Extract it into another gem?

Do you think you have something else to do than write in the changelog that the segment has disappeared? I don't think that someone would automatically update the gem without taking a look to the changes, it seems to be a very dangerous behaviour.

**Comment by mogox** [comment]
Yeah, we created this gem instead of adding another ZXX segment: https://github.com/ruby-hl7/ruby-hl7-zps.  I'll go ahead and create one gem for ZCF before merging this PR.

**Comment by mitch-lindsay** [comment]
Late to the game but I support removing the ZCF segment with a note in the change logs.

**Comment by rclavel** [comment]
Hey @mogox,
I just created the [`ruby-hl7-zcf` gem](https://github.com/doctolib/ruby-hl7-zcf). It's published on rubygems.
I guess this PR can now be merged? 🙂

**Comment by mogox** [comment]
Yes!
I'd be great if you can add a note on the read me but it can be done later.

**Pull request merged**
