### PR TITLE
Add CI with GitHub Actions

### PR DESCRIPTION
**Pull request by petergoldstein**
Adds CI with GitHub Actions.  Addresses a number of lints, and adds a `.rubocop_todo.yml` to handle the others.

Runs green on my fork.

### CODE REVIEW

**Comment by Stratus3D** [comment]
@petergoldstein thanks for the PR! I'm not active on this project anymore, so I can't really provide much feedback on these changes. I will say this is a very large diff, and it might be better to do things incremental. This PR does much more than setup CI with Github Actions, as many Ruby files are changed.

@LucasMontorio it might be good to switch this project over to Github Actions. I've been using Github Actions for most of my open source stuff in recent years.

**Comment by LucasMontorio** [comment]
> @petergoldstein thanks for the PR! I'm not active on this project anymore, so I can't really provide much feedback on these changes. I will say this is a very large diff, and it might be better to do things incremental. This PR does much more than setup CI with Github Actions, as many Ruby files are changed.
> 
> @LucasMontorio it might be good to switch this project over to Github Actions. I've been using Github Actions for most of my open source stuff in recent years.

Agreed. I will add this to my TODO list and try to do it in the following weeks

**Comment by LucasMontorio** [comment]
CI (with Github Actions) added in [this PR](https://github.com/ruby-hl7/ruby-hl7/pull/129), and Rubocop config added in [this PR](https://github.com/ruby-hl7/ruby-hl7/pull/131) :)

**Comment by LucasMontorio** [comment]
CI (with Github Actions) added in [this PR](https://github.com/ruby-hl7/ruby-hl7/pull/129), and Rubocop config added in [this PR](https://github.com/ruby-hl7/ruby-hl7/pull/131) :)

I'm closing this PR as it's now out-of-date and has a lot of conflicts, please don't hesitate to reopen it if you feel that some bits are missing from the recent additions.

**Pull request closed without merging**
